version: "2"
services:
  hub:
      container_name: hub
      image: selenium/hub:3.14.0-arsenic
      ports:
        - "4444:4444"
  firefox:
      container_name: firefox
      image: selenium/node-firefox-debug:3.14.0-arsenic
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - hub
      ports:
        - "32700:5900"
      environment:
        HUB_HOST: hub

  chrome:
      container_name: chrome
      image: selenium/node-chrome-debug:3.14.0-arsenic
      volumes:
        - /dev/shm:/dev/shm 
      depends_on:
        - hub
      ports:
        - "32701:5900"
      environment:
        HUB_HOST: hub
